# Generated by Django 4.2.27 on 2026-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0002_servicio_remove_vehiculo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
