# Generated by Django 4.2.27 on 2026-03-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0003_cita_recordatorio_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
    ]
