# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0003_cita_recordatorio_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('admin', 'Admin')], default='empleado', max_length=10),
        ),
    ]
