# Generated by Django 4.2.27 on 2026-03-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0004_perfil_rol'),
        ('carwashapp', '0006_categoria_producto_ordencafeteria_factura_and_more'),
    ]

    operations = [
    ]
