# Generated by Django 4.2.27 on 2026-03-21 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carwashapp', '0007_merge_20260320_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Empleado',
                'verbose_name_plural': 'Sesiones de Empleados',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
